baseURL = "https://www.baseline-protocol.org/"
languageCode = "en-us"
title = "Baseline"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 # number of sponsors that will show on sponsor page at a time
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/baseline_logos/favicon.ico"
  description = ""
  facebook = ""
  twitter = "https://twitter.com/baselineproto"
  instagram = ""
  youtube = ""
  github = "https://github.com/ethereum-oasis/baseline"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  logo = "/images/baseline_logos/baselineLogoMark-All-White.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/hero-bg.png"
  recent_posts_number = 1
  mailing_list_subscribe = "mailto:baseline-subscribe@lists.oasis-open-projects.org"
  custom_css = ["css/custom.css"]
  mainSections = ["news", "sponsors"]
